apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  selector:
    matchLabels:
      run: php-app
  replicas: 1
  template:
    metadata:
      labels:
        run: php-app
    spec:
      containers:
      - name: php-app
        image: rakshi123/phpapp:#{Build.BuildId}#
        ports:
        - containerPort: 80
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    run : php-app
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer

        
